### ISSUE TITLE
Oldest artifact is displayed on a badge

### ISSUE THREAD

**Issue by akoshman** [softwaremill/maven-badges#338]
Hi there,

Some artifacts present in maven repository doesn't follow semver convention, for example: https://mvnrepository.com/artifact/commons-io/commons-io

There is old artifact '20030203.000550' published in Nov, 2005 while the newest one is '2.7' published in May, 2020.

This results in displaying the oldest published artifact:

![](https://maven-badges.herokuapp.com/maven-central/commons-io/commons-io/badge.png?style=default)

Can we exclude such exceptional artifacts from being displayed on the badges?

**Comment by lukaszlenart** [comment]
This can be hard and you may consider removing such artifact from the Central, I think issuing a JIRA ticket should be enough
https://issues.sonatype.org/browse/OSSRH-33337

**Comment by lukaszlenart** [comment]
I added a new parameter `gav=true` which should fix your problem, just use

![]https://maven-badges.herokuapp.com/maven-central/commons-io/commons-io/badge.png?style=default&gav=true
