### ISSUE TITLE
semver redirect does not support gav=true

### ISSUE THREAD

**Issue by aherbert** [softwaremill/maven-badges#344]
The `gav=true` parameter works for the badge but not for the redirect to maven central. 

For example Commons Codec has a very old artifact that does not follow semver. Here are the badges:

[badge default](https://maven-badges.herokuapp.com/maven-central/commons-codec/commons-codec/badge.svg)
[badge gav=true](https://maven-badges.herokuapp.com/maven-central/commons-codec/commons-codec/badge.svg?gav=true)

But the redirect link with `gav=true` does not redirect to the version matching the badge:

[redirect default](https://maven-badges.herokuapp.com/maven-central/commons-codec/commons-codec)
[redirect gav=true](https://maven-badges.herokuapp.com/maven-central/commons-codec/commons-codec?gav=true)

If this is not an issue with this project then please let me know who to contact. Any help would be appreciated. Thanks.

**Comment by lukaszlenart** [comment]
Fixed :)

**Comment by aherbert** [comment]
Thanks for rapid turnaround. When will this fix be deployed to the live version?

**Comment by lukaszlenart** [comment]
It's already there, each push to Github redeploys a new version, constant CI & CD ;-)

**Comment by aherbert** [comment]
Thanks. I did try it after you pushed the fix (on that assumption) but the replication had not trickled through.

Keep up the good work.

**Comment by lukaszlenart** [comment]
Yeah... I was too eager and just second commit a0650ec8e2bf83c847d86aea70a30cda3fa54362 fixed the problem.
