### ISSUE TITLE
Add caching headers to avoid cached images in GitHub

### ISSUE THREAD

**Issue by Ekryd** [softwaremill/maven-badges#44]
Hi,

It seems that the images returned does not set correct cache headers. This means that the badge images does not update in GitHub documentation.

Please set 'Cache-Control: no-cache'

When I access:
https://maven-badges.herokuapp.com/maven-central/com.github.ekryd.sortpom/sortpom-maven-plugin/badge.svg

The following headers are set in the response:
ETag: W/"3c8-uXNJhUfhSbnAQuEe3YBxIwvwUOc"
Content-Type: image/svg+xml
Date: Sun, 30 Sep 2018 12:46:38 GMT
Cache-Control: public, max-age=43200
+ some custom headers

The header should be set like this to avoid caching issues:
**Cache-Control: no-cache**
and either Expires, Last-Modified or Etag. 

For additional information, please see the linked GitHub issue.
https://github.com/github/markup/issues/224#issuecomment-48532178

**Comment by lukaszlenart** [comment]
It is set to 12h period, is it a problem? We can reduce it, but setting it to `no-cache` will put a high load on the heroku node and then it will increase a cost (for us) of hosting this free service :)

**Comment by mosesn** [comment]
My suspicion is that github pulled a cached copy before maven-badges started returning the [12 hour max-age][0].  Try [purging][1] the camo caches, I think it should work going forward.

[0]: https://github.com/softwaremill/maven-badges/commit/3b54dd321f21355dca3402469d15ad6b48c25547
[1]: https://help.github.com/articles/about-anonymized-image-urls/#removing-an-image-from-camos-cache
