### ISSUE TITLE
Cache headers

### ISSUE THREAD

**Issue by Petrakeas** [softwaremill/maven-badges#445]
I use the maven badge το my GitHub's repo `readme.md`  and I noticed that after launching a new version to Maven Central, even though the maven-badge was showing the latest version, GitHub was serving the previous version for about 10 hours or more. 

My question is whether the etag and HTTP cache headers are implemented correctly and is GitHub that does not honor them soon enough or if there is room for improvement.

**Comment by lbruun** [comment]
It is all explained here:  [GitHub documentation on their image caching mechanism](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls#an-image-that-changed-recently-is-not-updating).

The gist of it is that the server hosting the SVG needs to return HTTP header:

    Cache-Control: no-cache

Unless the server does this the image will not update, at least not immediately. I haven't been able to get GitHub's `PURGE` feature (explained in same link) to have any effect.

Anyways, this project has its auto-generated SVG's hosted on `maven-badges.herokuapp.com` and this server sets the HTTP header as follows:

    Cache-Control: public, max-age=43200

(so 12 hours caching)

Clearly not what we want and possibly the cause of the problems.  I appreciate that SoftwareMill is (paying for) hosting this and thus providing a free service to the community. I would think that `no-cache` might overload the backend and wouldn't be feasible? In any case a compromise needs to be found. Maybe 1 hour?   At the very least this needs to be documented.

**Comment by lbruun** [comment]
Ahh. This issue very much similar #44.

**Comment by lukaszlenart** [comment]
I think this one can be closed, thanks a lot @lbruun for the explanation :)
