### ISSUE TITLE
Badge not updating

### ISSUE THREAD

**Issue by lbergelson** [softwaremill/maven-badges#5]
I noticed that our badge stopped updating to show the newest version of our software.  It shows `4.0.5.2` instead of `4.0.6.0`.  If you click the badge it correctly directs to the 4.0.6.0 page.  

Our project is https://github.com/broadinstitute/gatk.  The timeline seems to correspond to the change from ruby -> node.js.  

Let me know if there's any more information that can help.  Thank you for providing this service.

**Comment by belfz** [comment]
@lbergelson Thanks. It looks like a problem with GitHub's image caching - when I opened https://maven-badges.herokuapp.com/maven-central/org.broadinstitute/gatk/badge.svg directly in the browser (that's the URL you're using for the badge), it returned me a badge with `4.0.6.0` version, as expected. Maybe [this SO answer could help](https://stackoverflow.com/questions/26898052/how-to-force-image-cache-update-in-readme-rst-on-github)?

**Comment by lbergelson** [comment]
@belfz Interesting, thank you looking into it.  I didn't even realize github did image caching.

**Comment by ferstl** [comment]
I'm encountered the same problem and switched temporarily to the shields.io badge.
According to https://github.com/github/markup/issues/224#issuecomment-48532178 you should set the "`Cache-Control: no-cache` header, and either `Expires`, `Last-Modified` or `Etag`.

When looking at your example badge, I see that you set `max-age` in the Cache-Control header. Maybe that's the problem.

```
curl -v https://maven-badges.herokuapp.com/maven-central/cz.jirutka.rsql/rsql-parser/badge.svg

...
< Cache-Control: public, max-age=43200
< Etag: ..."
...
```
