### ISSUE TITLE
Badges show "unknown" version

### ISSUE THREAD

**Issue by Akii** [softwaremill/maven-badges#620]
Probably some change upstream. It's visible on this repos readme as well.
Seems like the query is no longer working.

**Comment by TWiStErRob** [comment]
Just wanted to report the same, not only "unknown", but also the search doesn't work:
e.g.
https://github.com/ReactiveX/RxJava

[![Maven Central](https://maven-badges.herokuapp.com/maven-central/io.reactivex.rxjava3/rxjava/badge.svg)](https://maven-badges.herokuapp.com/maven-central/io.reactivex.rxjava3/rxjava)

Image: https://maven-badges.herokuapp.com/maven-central/io.reactivex.rxjava3/rxjava/badge.svg
Link: https://maven-badges.herokuapp.com/maven-central/io.reactivex.rxjava3/rxjava

redirects to: https://search.maven.org/search?g:io.reactivex.rxjava3+AND+a:rxjava&core=gav
redirects to: https://search.maven.org/search?g:io.reactivex.rxjava3%20AND%20a:rxjava=&core=gav

Corrects search (note the `q=`): https://search.maven.org/search?q=g:io.reactivex.rxjava3%20AND%20a:rxjava

**Comment by lukaszlenart** [comment]
The badge itself is ok as far I see, it displays a proper version. There is some JS trick happening on the search page, see https://search.maven.org/artifact/io.reactivex.rxjava3/rxjava/3.1.4/jar and then switch to 3.13 and back to 3.14 - the url is ok, JS does the magic.

**Comment by lukaszlenart** [comment]
ech.. it is something else, check JS console when opening https://search.maven.org/artifact/io.reactivex.rxjava3/rxjava/3.1.4/jar - it shows an error
```
GET https://search.maven.org/remotecontent?filepath=io/reactivex/rxjava3/rxjava/3.1.4/rxjava-3.1.4.pom 404
...
ERROR x {headers: m, status: 404, statusText: 'OK', url: 'https://search.maven.org/remotecontent?filepath=io/reactivex/rxjava3/rxjava/3.1.4/rxjava-3.1.4.pom', ok: false, …}
```

using https://search.maven.org/artifact/io.reactivex.rxjava3/rxjava/3.1.3/jar works ok so it must be something with Maven repo sync, the pom of 3.1.4 is not available.

**Comment by lukaszlenart** [comment]
Here is the problem https://search.maven.org/remotecontent?filepath=io/reactivex/rxjava3/rxjava/3.1.4/rxjava-3.1.4.pom but I have no idea why it works for https://search.maven.org/remotecontent?filepath=io/reactivex/rxjava3/rxjava/3.1.3/rxjava-3.1.3.pom

**Comment by lukaszlenart** [comment]
I have reported the issue to https://issues.sonatype.org/projects/MVNCENTRAL

**Comment by Akii** [comment]
Seems to work again. Maybe it was something temporary after all.

**Comment by lukaszlenart** [comment]
The badge is ok, but there is still problem on Maven repo with the broken link

**Comment by lukaszlenart** [comment]
The broken link has been fixed

**Comment by TWiStErRob** [comment]
Nice one, confirmed working as expected.

**Comment by Akii** [comment]
Thank you!
