### ISSUE TITLE
Badges broken since the last automated pull request?

### ISSUE THREAD

**Issue by romainguy** [softwaremill/maven-badges#703]
Badges and their URLs have stopped working properly since yesterday. For instance:

`https://maven-badges.herokuapp.com/maven-central/dev.romainguy/combo-breaker/badge.svg?subject=combo-breaker`

Gives the following result in the browser:

```
This page contains the following errors:
error on line 1 at column 1: Encoding error
Below is a rendering of the page up to the first error.
```

When omitting the `subject` parameter, a badge is generated but the right-hand side of the badge always says "unknown":

`https://maven-badges.herokuapp.com/maven-central/dev.romainguy/combo-breaker/badge.svg`

Generates:

![](https://maven-badges.herokuapp.com/maven-central/dev.romainguy/combo-breaker/badge.svg)

**Comment by lukaszlenart** [comment]
It's a bug in the latest Axios, reverted to the previous version.

**Comment by romainguy** [comment]
Thank you!

**Comment by lukaszlenart** [comment]
Related to https://github.com/axios/axios/issues/5319
