### ISSUE TITLE
badge shows unknown instead of version

### ISSUE THREAD

**Issue by mwiede** [softwaremill/maven-badges#912]
if I curl the svg and open the downloaded file in a browser, it shows the version
`curl https://maven-badges.herokuapp.com/maven-central/com.github.mwiede/jsch/badge.svg -O`
but when I right click and "open image in a new tab" then the url says https://camo.githubusercontent.com/fc07432a80e32364bf892c5864038ae0dd12ceb62e68f28a75157f8ba056a9fc/68747470733a2f2f6d6176656e2d6261646765732e6865726f6b756170702e636f6d2f6d6176656e2d63656e7472616c2f636f6d2e6769746875622e6d77696564652f6a7363682f62616467652e737667 and the version shows **unknown**.

When reloading the browser with https://maven-badges.herokuapp.com/maven-central/com.github.mwiede/jsch/badge.svg it flickers between the correct version and unknown.

**Comment by seljabali** [comment]
The readme also shows unknown version across the board.

**Comment by activey** [comment]
I'm also having the same issue, my badge just displays "unknown" instead of version :(

**Comment by lukaszlenart** [comment]
Maybe it was a temporary issue, which happens. Now all looks good
